# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ce14bdd8857c007dacce56d1b7caaeeba111763bf92986cfb462637b72d0dba9e043990298cb120cddf3e4060ffae6bfb89aab86f0691f0152af0eeb29095ba3

test:
  secret_key_base: 174971176f41d35df3a1fac8224ef3d956c39795791181bcfb028842465ad63e82381670bbbbaeaaa6daad6e6754fcf76fe51ab194cf7647d5e8a5c807a1d127

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
